name: TeleportExtensionPlugin
version: '1.1'
main: jp.bismaschiruo.tpextension.tpextension.teleportextensionplugin.TeleportExtensionPlugin
api-version: 1.17
authors: [ Bismas ]

commands:
  tpe:
    description: Description
    usage: /tutorial